[tool.poetry]
name = "heisenbug"
version = "0.1.0"
description = "Demo app"
authors = ["sobolevn <mail@sobolevn.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6"
flask = "^1.0"
safety = "^1.8"

[tool.poetry.dev-dependencies]
mypy = "^0.670"
wemake-python-styleguide = "^0.7"

pytest = "^4.3"
pytest-cov = "^2.6"
pytest-randomly = "^1.2"
pytest-testmon = "^0.9.15"
pytest-timeout = "^1.3"
hypothesis = "^4.11"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
